version: "3.8"

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 87654321
      MYSQL_DATABASE: coding_challenge
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
